version: "3"
services:
  db:
    container_name: sqlserver
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "1433:1433"
    volumes:
      - ./seed.sql:/scripts/
    environment:
      SA_PASSWORD: "Your_Password_123"
      ACCEPT_EULA: "Y"
